
[Novice]
JobRank = 0
[Novice.SkillTree]
BasicMastery = []
FirstAid = [["BasicMastery", 2]]

[Swordsman]
JobRank = 1
Extends = "Novice"
[Swordsman.SkillTree]
SwordMastery = []
TwoHandSwordMastery = [["SwordMastery", 1]]
IncreasedHPRecovery = []
Bash = []
MagnumBreak = [["Bash", 5]]
Provoke = []
Endure = [["Provoke", 5]]
ChargeAttack = [["Bash", 7], ["MagnumBreak", 3]]
TwoHandQuicken = [["TwoHandSwordMastery", 10], ["Endure", 5]] #just for testing

[Archer]
JobRank = 1
Extends = "Novice"
[Archer.SkillTree]
OwlEye = []
VultureEye = [["OwlEye", 3]]
DoubleStrafe = []
ArrowShower = [["DoubleStrafe", 10]]
ImproveConcentration = [["VultureEye", 1]]
ChargeArrow = [["OwlEye", 5], ["VultureEye", 5]]
BeastBane = [["OwlEye", 10]]
AnkleSnare = [["ImproveConcentration", 10], ["BeastBane", 10]]

[Mage]
JobRank = 1
Extends = "Novice"
[Mage.SkillTree]
IncreaseSPRecovery = []
FireBolt = []
FireBall = [["FireBolt", 4]]
FireWall = [["Sight", 1], ["FireBall", 5]]
LightningBolt = []
ThunderStorm = [["LightningBolt", 4]]
ColdBolt = []
FrostDiver = [["ColdBolt", 5]]
Sight = []
NapalmBeat = []
SoulStrike = [["NapalmBeat", 4]]
SafetyWall = [["NapalmBeat", 7], ["SoulStrike", 5]]
StoneCurse = []
EarthSpike = [["StoneCurse", 3]]
HeavensDrive = [["EarthSpike", 3]]
WaterBall = [["FrostDiver", 7], ["LightningBolt", 3]]
EnergyCoat = [["FireBolt", 3], ["ColdBolt", 3], ["LightningBolt", 3]]

[Acolyte]
JobRank = 1
Extends = "Novice"
[Acolyte.SkillTree]
DivineProtection = []
DemonBane = [["DivineProtection", 1]]
Heal = []
Angelus = [["DivineProtection", 3]]
Blessing = [["DivineProtection", 5]]
IncreaseAgility = [["Heal", 3]]
DecreaseAgility = [["IncreaseAgility", 1]]
Cure = [["Heal", 2]]
Ruwach = []
Teleport = [["Ruwach", 1]]
Return = [["Teleport", 1]]
WarpPortal = [["Return", 1]]
Pneuma = [["WarpPortal", 4]]
HolyLight = [["DemonBane", 1]]
SignumCrusis = [["DemonBane", 3]]
AquaBenedicta = []

[Thief]
JobRank = 1
Extends = "Novice"
[Thief.SkillTree]
DoubleAttack = []
ImproveDodge = []
Envenom = []
Detoxify = [["Envenom", 3]]
Steal = []
Hiding = [["Steal", 5]]
#SandAttack = [["Envenom", 5]]
BackSlide = [["ImproveDodge",5]]
#FindStone = []
SonicBlow = [["DoubleAttack", 5],["Envenom", 7]]
EnchantPoison = [["Envenom", 10],["Hiding", 3]]

[Merchant]
JobRank = 1
Extends = "Novice"
[Merchant.SkillTree]
EnlargeWeightLimit = []
Discount = [["EnlargeWeightLimit",3]]
Overcharge = [["Discount",3]]
PushCart = [["EnlargeWeightLimit",5]]
Vending = [["PushCart",3]]
ItemAppraisal = [["Discount",5]]
Mammonite = []
CrazyUproar = [["Mammonite", 3], ["ItemAppraisal", 1]]
CartRevolution = [["PushCart", 10], ["CrazyUproar", 1]]
HammerFall = [["EnlargeWeightLimit",5]]
AdrenalineRush = [["ItemAppraisal",5],["Overcharge",5],["PushCart",5]]

[Priest]
JobRank = 2
Extends = "Acolyte"
[Priest.SkillTree]
IncreaseSPRecovery = []
StatusRecovery = []
Resurrection = [["IncreaseSPRecovery",4],["StatusRecovery",1]]
ImpositioManus = []
Aspersio = [["AquaBenedicta",1],["ImpositioManus",3]]
Sanctuary = [["Heal", 1]]
SafetyWall = [["Aspersio", 4],["Sanctuary", 3]]
